### ISSUE TITLE
Hur funkar plot(self, points)

### ISSUE THREAD

**Issue by SamuelWiqvist** [SamuelWiqvist/FMNN25Project1#2]
I plot(self, points) gissar jag att points är punkterna som man vill plotta, eller? Dock är jag inte helt med på varför vi behöver skicka med punkter som funktionen ska plotta hela kurvan...

**Comment by SamuelWiqvist** [comment]
Ok! vet hur funktionen funkar nu

**Comment by linuslinus** [comment]
Jo points är ett missvisande variabelnamn, number_of_points hade varit bättre.

**Comment by ASamarkRoth** [comment]
Ändrat precis till number_of_points. Sedan hade du Samuel i plot tagit
nbr_of_points -3, ska det inte vara -2? Jag ändrade till -2.

Tänkte på en annan grej. Vi har bara linjära "linjer" i plotten, kan det
bero på något i _blossom?
